name: BuildTest

on:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2-beta
    - uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: StandaloneLinux64
        unityVersion: 2021.1.18f1